# Generated by Django 6.0.2 on 2026-02-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
